; BACKGROUNDTILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 10
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

; SECTION "Tiles", HOME

; Start of tile array.
Section "Background Tile Data", ROM0[$2200]

BackgroundTileData:
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$38,$38,$28,$28
DB $38,$28,$28,$28,$38,$38,$00,$00
DB $00,$00,$00,$00,$38,$08,$28,$08
DB $38,$08,$28,$08,$38,$08,$00,$00
DB $00,$00,$00,$00,$38,$38,$28,$08
DB $38,$38,$28,$20,$38,$38,$00,$00
DB $00,$00,$00,$00,$38,$38,$28,$08
DB $38,$38,$28,$08,$38,$38,$00,$00
DB $00,$00,$00,$00,$38,$28,$28,$28
DB $38,$38,$28,$08,$38,$08,$00,$00
DB $00,$00,$00,$00,$38,$38,$28,$20
DB $38,$38,$28,$08,$38,$38,$00,$00
DB $00,$00,$00,$00,$38,$38,$28,$20
DB $38,$38,$28,$28,$38,$38,$00,$00
DB $00,$00,$00,$00,$38,$38,$28,$08
DB $38,$08,$28,$08,$38,$08,$00,$00
DB $00,$00,$00,$00,$38,$38,$28,$28
DB $38,$38,$28,$28,$38,$38,$00,$00
DB $00,$00,$00,$00,$38,$38,$28,$28
DB $38,$38,$28,$08,$38,$38,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$E4,$E4,$AA,$AA,$EE,$EE
DB $8A,$8A,$8A,$8A,$00,$00,$00,$00
DB $00,$00,$AE,$AE,$A2,$A2,$A4,$A4
DB $A8,$A8,$EE,$EE,$00,$00,$00,$00
DB $00,$00,$EC,$EC,$8A,$8A,$EA,$EA
DB $8A,$8A,$EC,$EC,$00,$00,$00,$00
BackgroundTileDataEnd

; End of BACKGROUNDTILES.Z80
