; SPRITETILEDATA.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 3
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

; SECTION "Tiles", ROM0

Section "Sprite Tile Data", ROM0[$2000]

; ; Start of tile array.
SpriteTileData:
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$FF,$81,$FF,$A5,$FF,$81
DB $FF,$A5,$FF,$BD,$FF,$81,$FF,$FF
DB $FF,$FF,$DB,$A5,$E7,$BD,$FF,$81
DB $FF,$BD,$FF,$A5,$FF,$81,$FF,$FF
DB $18,$18,$24,$3C,$66,$5A,$99,$E7
DB $99,$E7,$66,$5A,$24,$3C,$18,$18
SpriteTileDataEnd;
; End of SPRITETILEDATA.Z80
